# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.0.1
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==0.5.2
    - sphinx-inline-tabs==2021.4.11b9